# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bill Castillo
email: castillobil@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Front-end / web designer and developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://billcastillo.me" # the base hostname & protocol for your site

# Social Media
twitter_username: castlenibill
github_username:  billcastillo
codepen_username: billcastillo

# Build settings
markdown: kramdown
timezone: Asia/Dubai
highlighter: rouge
