
# Site settings
title: Bill Castillo
email: castillobil@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Front-end Developer & Designer. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://billcastillo.me" # the base hostname & protocol for your site
codepen_username: billcastillo
github_username:  billcastillo

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]
post_dirs: false

# collections:
#   projects:
#     output: true
#     permalink: /projects/:path/